In [1]:
#Import The Libraries

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import pandas as pd
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

In [3]:
def split_scalar(X,y):
    from sklearn.model_selection import train_test_split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
    return X_train,X_test,y_train, y_test

def perform_lda(indpen_X,dep_Y, n=1):
    lda = LDA(n_components = n-1)
    X_train = lda.fit_transform(indpen_X,dep_Y)
    return lda, X_train

In [4]:
def logistic(X_train, y_train,X_test):
    from sklearn.linear_model import LogisticRegression
    classifier = LogisticRegression(random_state = 0)
    classifier.fit(X_train, y_train)
    cm,accuracy,classifier = cm_predition(classifier,X_test)
    return cm,accuracy,classifier

def svm_linear(X_train,y_train,X_test):
    from sklearn.svm import SVC
    classifier = SVC(kernel = 'linear', random_state = 0)
    classifier.fit(X_train, y_train)
    cm,accuracy,classifier = cm_predition(classifier,X_test)
    return  cm,accuracy,classifier

def svm_NL(X_train,y_train,X_test):
    from sklearn.svm import SVC
    classifier = SVC(kernel = 'rbf', random_state = 0)
    classifier.fit(X_train, y_train)
    cm,accuracy,classifier = cm_predition(classifier,X_test)
    return  cm,accuracy,classifier

def Navie(X_train,y_train,X_test):
    # Fitting K-NN to the Training set
    from sklearn.naive_bayes import GaussianNB
    classifier = GaussianNB()
    classifier.fit(X_train, y_train)
    cm,accuracy,classifier = cm_predition(classifier,X_test)
    return  cm,accuracy,classifier


def knn(X_train,y_train,X_test):
    # Fitting K-NN to the Training set
    from sklearn.neighbors import KNeighborsClassifier
    classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
    classifier.fit(X_train, y_train)
    cm,accuracy,classifier = cm_predition(classifier,X_test)
    return  cm,accuracy,classifier

def Decision(X_train,y_train,X_test):
    # Fitting K-NN to the Training set
    from sklearn.tree import DecisionTreeClassifier
    classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
    classifier.fit(X_train, y_train)
    cm,accuracy,classifier = cm_predition(classifier,X_test)
    return  cm,accuracy,classifier


def random(X_train,y_train,X_test):
    # Fitting K-NN to the Training set
    from sklearn.ensemble import RandomForestClassifier
    classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
    classifier.fit(X_train, y_train)
    cm,accuracy,classifier = cm_predition(classifier,X_test)
    return  cm,accuracy,classifier

def cm_predition (classifier,X_test):
    y_pred = classifier.predict(X_test)
    from sklearn.metrics import confusion_matrix
    cm = confusion_matrix(y_test, y_pred)
    from sklearn.metrics import accuracy_score
    accuracy= accuracy_score(y_test, y_pred)
    return cm,accuracy,classifier

In [5]:
def lda_merge(acclog,accsvmlin,accsvmnl,accnav,accknn,accdec,accrand):
    dataframe=pd.DataFrame(index=['LDA n=2'],columns=['Logistic','SVMlin','SVMNL','Navie','KNN','DT','RF'])
    for number,index in enumerate(dataframe.index):
        dataframe['Logistic'][index]=acclog[number]
        dataframe['SVMlin'][index]=accsvmlin[number]
        dataframe['SVMNL'][index]=accsvmnl[number]
        dataframe['Navie'][index]=accnav[number]
        dataframe['KNN'][index]=accknn[number]
        dataframe['DT'][index]=accdec[number]
        dataframe['RF'][index]=accrand[number]
    return dataframe

In [6]:
dataset = pd.read_csv("dataset_preprocess_ds.csv", index_col=None)

dataset = pd.get_dummies(dataset, drop_first=True)

In [7]:
dataset

,Crop/Year,Area_Hectares,Production_Tonnes,District_Name_BEED,District_Name_HINGOLI,District_Name_JALNA,District_Name_LATUR,District_Name_NANDED,District_Name_OSMANABAD,Winter/Summer_Rabi,...,Rice_Niger seed,Rice_Other Rabi pulses,Rice_Other Kharif pulses,Rice_Rice,Rice_Safflower,Rice_Sesamum,Rice_Soyabean,Rice_Sugarcane,Rice_Sunflower,Rice_Wheat
0,2014,32900,8700.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2014,45300,24200.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2014,101675,61475.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2014,4100,900.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2014,3700,1700.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,2014,24100,7100.0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,1
147,2014,1900,800.0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
148,2014,1300,NaN,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
149,2014,500,200.0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
150,2014,39800,61475.0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0

In [8]:
dataset.columns

Index(['Crop/Year', 'Area_Hectares', 'Production_Tonnes', 'District_Name_BEED',
       'District_Name_HINGOLI', 'District_Name_JALNA', 'District_Name_LATUR',
       'District_Name_NANDED', 'District_Name_OSMANABAD',
       'Winter/Summer_Rabi       ', 'Winter/Summer_Summer     ',
       'Winter/Summer_Whole Year ', 'Rice_Bajra', 'Rice_Castor seed',
       'Rice_Cotton(lint)', 'Rice_Gram', 'Rice_Groundnut', 'Rice_Jowar',
       'Rice_Linseed', 'Rice_Maize', 'Rice_Moong(Green Gram)',
       'Rice_Niger seed', 'Rice_Other  Rabi pulses',
       'Rice_Other Kharif pulses', 'Rice_Rice', 'Rice_Safflower',
       'Rice_Sesamum', 'Rice_Soyabean', 'Rice_Sugarcane', 'Rice_Sunflower',
       'Rice_Wheat'],
      dtype='object')

In [9]:
indep_X = dataset.drop(['Crop/Year', 'Area_Hectares', 'Production_Tonnes'], axis=1)
dep_Y = dataset['Rice_Sugarcane']

In [10]:
lda, X_train_lda =perform_lda(indep_X,dep_Y,2) # n_components set to 1 for binary classification
# created a empty list to append the final value
acclog=[]
accsvmlin=[]
accsvmnl=[]
accnav=[]
accknn=[]
accdec=[]
accrand=[]

In [11]:
X_train, X_test, y_train, y_test=split_scalar(X_train_lda,dep_Y)

cm,accuracy,classifier=logistic(X_train,y_train,X_test)
acclog.append(accuracy)

cm,accuracy,classifier=svm_linear(X_train,y_train,X_test)
accsvmlin.append(accuracy)

cm,accuracy,classifier=svm_NL(X_train,y_train,X_test)
accsvmnl.append(accuracy)

cm,accuracy,classifier=Navie(X_train,y_train,X_test)
accnav.append(accuracy)

cm,accuracy,classifier=knn(X_train,y_train,X_test)
accknn.append(accuracy)

cm,accuracy,classifier=Decision(X_train,y_train,X_test)
accdec.append(accuracy)

cm,accuracy,classifier=random(X_train,y_train,X_test)
accrand.append(accuracy)
    
result =lda_merge(acclog,accsvmlin,accsvmnl,accnav,accknn,accdec,accrand)

C:\Users\sreet\anaconda3\envs\aidl\Lib\site-packages\sklearn\metrics\_classification.py:395: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
C:\Users\sreet\anaconda3\envs\aidl\Lib\site-packages\sklearn\metrics\_classification.py:395: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
C:\Users\sreet\AppData\Local\Temp\ipykernel_1836\2702623332.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['Logistic'][index]=acclog[number]
C:\Users\sreet\AppData\Local\Temp\ipykernel_1836\2702623332.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['SVMlin'][index]=accsvmlin[number]
C:\Users\sreet\AppData\Local\Temp\ipykernel_1836\2702623332.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['SVMNL'][index]=accsvmnl[number]
C:\Users\sreet\AppData\Local\Temp\ipykernel_1836\2702623332.py:7: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['Navie'][index]=accnav[number]
C:\Users\sreet\AppData\Local\Temp\ipykernel_1836\2702623332.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['KNN'][index]=accknn[number]
C:\Users\sreet\AppData\Local\Temp\ipykernel_1836\2702623332.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['DT'][index]=accdec[number]
C:\Users\sreet\AppData\Local\Temp\ipykernel_1836\2702623332.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['RF'][index]=accrand[number]

In [12]:
result

        Logistic    SVMlin     SVMNL     Navie  KNN        DT        RF
LDA n=2      1.0  0.967742  0.967742  0.967742  1.0  0.967742  0.967742

In [16]:
#Result KNN-Navie Baiyes is Best Model